export const usersActionTypes = {
  REQUEST_INIT: "USER_REQUEST_INIT",
  POST_REQUEST: "USER_POST_REQUEST",
  PUT_REQUEST: "USER_PUT_REQUEST",
  REQUEST_SUCCEED: "USER_REQUEST_SUCCEED",
  REQUEST_FAILED: "USER_REQUEST_FAILED"
};
